### ISSUE TITLE
Python Implementation Tracker

### ISSUE THREAD

**Issue by canewsin** [canewsin/zeronet-rs#28]
## Modules Need to be Implemeted(Python Repo)

 - [ ] User
 - [ ] Site(Storage, Announcer)
 - [ ] Content
 - [ ] File(FileServer)
 - [ ] Database
 - [ ] Connection
 - [ ] Peer(Peer Commands)
 - [ ] Ui(Server, Websockets)
 - [ ] Crypt
 - [ ] Translate
 - [ ] Tor
 - [ ] utils(diff, msgpack, upnp punch, rate limit etc)
 - [ ] Plugin
